import type { Dictionary } from "./types";
import { mergeProjects } from "./projects";

const en: Dictionary = {
  meta: {
    title: "Egor Trefilov — Python Backend & AI Automation Developer",
    description:
      "Portfolio of Egor Trefilov — Python Backend & AI Automation Developer building backend systems, AI-powered applications and automation tools.",
  },
  nav: {
    about: "About",
    capabilities: "Capabilities",
    projects: "Projects",
    experience: "Experience",
    stack: "Stack",
    resume: "Resume",
    contact: "Contact",
    menu: "Menu",
    close: "Close",
  },
  loader: { forming: "Assembling core" },
  hero: {
    label: "Backend / AI / Automation",
    first: "Egor",
    last: "Trefilov",
    role: "Python Backend &\nAI Automation Developer",
    summary:
      "I design backend systems, AI-powered applications and automation tools — with an emphasis on architecture, reliability and real use.",
    explore: "Explore work",
    contact: "Contact",
    available: "Available for opportunities",
    locationNote: "Independent / Freelance",
  },
  about: {
    index: "01",
    label: "About",
    statement: "Systems that stay useful after the demo.",
    paragraphs: [
      "I’m Egor Trefilov, a Python Backend & AI Automation Developer.",
      "I like systems that stay understandable after the first version: clear boundaries, reliable data flow and behaviour you can reason about.",
      "Backend, AI and automation interest me for the same reason. They turn a messy workflow into something repeatable.",
      "My core stack is Python, FastAPI, PostgreSQL, SQLAlchemy, Docker and modern AI/LLM integrations. I also work across mobile, desktop and machine-learning projects when the problem requires it.",
    ],
  },
  capabilities: {
    index: "02",
    label: "Capabilities",
    title: "What I do",
    items: [
      {
        index: "01",
        title: "Backend Systems",
        tags: "FastAPI · PostgreSQL · REST APIs · Background Jobs",
        body: "Building backend services, APIs and data-driven systems with a focus on clean architecture and reliability.",
      },
      {
        index: "02",
        title: "AI Integration",
        tags: "LLM · RAG · AI Workflows · Data Processing",
        body: "Integrating AI into practical products through LLM APIs, retrieval pipelines and automation workflows.",
      },
      {
        index: "03",
        title: "Automation",
        tags: "Bots · Parsers · External APIs · Workflow Automation",
        body: "Building automation tools that connect services, process data and remove repetitive manual work.",
      },
      {
        index: "04",
        title: "Desktop & Cross-platform",
        tags: "Flutter · .NET · WinUI · C++",
        body: "Desktop and cross-platform tools when the work belongs on a device, not only behind an API.",
      },
    ],
  },
  experience: {
    index: "03",
    label: "Experience",
    title: "Building services, not slides.",
    role: "Python Backend & AI Automation Developer",
    employment: "Independent / Freelance",
    period: "August 2025 — Present",
    intro: "Independent work since August 2025, across backend services, AI integrations and practical automation.",
    tracksTitle: "Focus",
    tracks: [
      { period: "2025 — now", title: "Backend services", body: "REST APIs, PostgreSQL, SQLAlchemy, Alembic, authentication and background jobs." },
      { period: "2025 — now", title: "AI integrations", body: "LLM APIs, RAG pipelines and usage-aware AI features inside real products." },
      { period: "2025 — now", title: "Automation", body: "Telegram bots, parsers, external APIs and data-processing scripts." },
    ],
    builtTitle: "What I build",
    built: [
      "Backend services",
      "REST APIs",
      "Telegram bots",
      "Parsers",
      "Automation tools",
      "Websites",
      "Data-processing scripts",
    ],
    practiceTitle: "In practice",
    practice: [
      "Python / FastAPI",
      "PostgreSQL",
      "SQLAlchemy",
      "Alembic migrations",
      "Authentication",
      "Session management",
      "External APIs",
      "LLM integrations",
      "RAG",
      "Background jobs",
      "Docker",
      "CI",
      "Automated tests",
      "Scraping",
      "Data processing",
    ],
  },
  projects: {
    index: "04",
    label: "Selected work",
    title: "Case studies",
    purpose: "Purpose",
    built: "What I built",
    highlights: "Engineering",
    technology: "Technology",
    github: "GitHub",
    active: "Active development",
    items: mergeProjects([
      {
        name: "AI Python Mentor",
        status: "Active development",
        statement: "A full-stack AI-powered platform for learning Python and backend development.",
        purpose:
          "A learning environment where an AI tutor, structured paths and coding practice live next to a real backend.",
        built:
          "Authentication and sessions, PostgreSQL migrations, learning paths, an AI tutor with RAG, Python practice, background jobs, AI usage accounting, email and Telegram integrations, CI, and a separated architecture for executing Python safely.",
        highlights: [
          "Authentication and session management",
          "PostgreSQL migrations",
          "Structured learning paths",
          "AI tutor and RAG",
          "Python coding practice",
          "Background jobs",
          "AI usage accounting",
          "Email / Telegram integrations",
          "CI",
          "Secure separated Python execution",
        ],
      },
      {
        name: "NGIE University App",
        statement: "A cross-platform university app with offline data, schedule notifications and native widgets.",
        purpose: "A daily tool for a university schedule that still works offline and on the lock screen.",
        built:
          "A feature-oriented Flutter application with local storage, a network and cache layer, schedule notifications, iOS widgets including the lock screen, Android integrations and mobile CI.",
        highlights: [
          "Feature-oriented architecture",
          "Offline storage",
          "Network and cache layer",
          "University schedule",
          "Notifications",
          "iOS native widgets",
          "Lock-screen widgets",
          "Android integrations",
          "Mobile CI",
        ],
      },
      {
        name: "TransactionMonitor",
        statement: "A desktop application for transaction monitoring and risk analysis.",
        purpose: "A desktop workspace for watching transactions, clients and counterparties with a risk lens.",
        built:
          "Monitoring, risk scoring, an analytics dashboard, records for clients, accounts and counterparties, risk analysis and CSV export.",
        highlights: [
          "Transaction monitoring",
          "Risk scoring",
          "Analytics dashboard",
          "Clients, accounts, counterparties",
          "Risk analysis",
          "CSV export",
        ],
      },
      {
        name: "Neural A* Heuristic",
        statement:
          "A PyTorch network learns to estimate distance-to-solution and becomes the heuristic inside A* search.",
        purpose: "Replace a hand-written heuristic with a learned value function without leaving classical search.",
        built:
          "Solved states are walked backward into a training set. A neural value function V(s) estimates distance-to-solution and guides A*.",
        highlights: [
          "Solved state → backward walks",
          "Training dataset",
          "Neural value function V(s)",
          "A* search",
          "Solution",
        ],
      },
      {
        name: "K-Nearest Neighbors from Scratch",
        statement: "k-NN classification written from scratch in C++17, with a desktop GUI.",
        purpose: "A transparent classifier: distances, votes and the dataset stay visible.",
        built:
          "Euclidean, Manhattan and cosine distance, weighted voting, feature normalization, CSV datasets and a desktop visualization.",
        highlights: [
          "Euclidean distance",
          "Manhattan distance",
          "Cosine distance",
          "Weighted voting",
          "Feature normalization",
          "CSV datasets",
          "Desktop visualization",
        ],
      },
    ]),
  },
  stack: {
    index: "05",
    label: "Technology",
    title: "A stack I actually ship with.",
    groups: [
      {
        name: "Backend",
        items: ["Python", "FastAPI", "PostgreSQL", "SQLAlchemy", "Alembic", "REST APIs", "AsyncIO"],
      },
      {
        name: "AI / Data",
        items: ["LLM APIs", "RAG", "PyTorch", "Pandas", "Data Processing", "Automation"],
      },
      {
        name: "Infrastructure",
        items: ["Docker", "Git", "GitHub Actions", "Linux", "CI"],
      },
      {
        name: "Additional",
        items: ["Next.js", "TypeScript", "Flutter", "Dart", "C#", ".NET", "C++17", "Swift"],
      },
    ],
  },
  resume: {
    index: "06",
    label: "Resume",
    title: "On paper, briefly.",
    name: "Egor Trefilov",
    role: "Python Backend & AI Automation Developer",
    profileTitle: "Profile",
    profile: "Backend developer focused on Python, FastAPI, PostgreSQL and AI/LLM integrations.",
    experienceTitle: "Experience",
    educationTitle: "Education",
    skillsTitle: "Core skills",
    skills: ["Python", "Backend Development", "FastAPI", "PostgreSQL", "Docker", "REST APIs", "SQLAlchemy", "AI / LLM", "RAG"],
    workTitle: "Selected work",
    download: "Download Resume PDF",
    view: "View GitHub Resume",
  },
  education: {
    index: "07",
    label: "Education",
    school: "NGIEU",
    program: "Systems of Artificial Intelligence",
    period: "2024 — Present",
  },
  contact: {
    index: "08",
    label: "Contact",
    title: "Let's build something useful.",
    status: "Available for work / freelance / collaboration",
    cta: "Contact me",
    github: "View GitHub",
    copyEmail: "Copy email",
    copyTelegram: "Copy Telegram",
    copied: "Copied",
    email: "Email",
    telegram: "Telegram",
    linkedin: "LinkedIn",
    resume: "Resume",
  },
  footer: {
    role: "Python Backend / AI / Automation",
    rights: "Egor Trefilov",
  },
  a11y: {
    themeToLight: "Switch to light theme",
    themeToDark: "Switch to dark theme",
    themeLight: "Light",
    themeDark: "Dark",
    lang: "Language",
    skip: "Skip to content",
    orb: "Decorative neural core",
    notFound: { title: "This page is not here.", body: "The address does not match anything on the site.", back: "Back home" },
  },
};

export default en;
