import type { Dictionary } from "./types";
import { mergeProjects } from "./projects";

const ru: Dictionary = {
  meta: {
    title: "Егор Трефилов — Python Backend & AI Automation Developer",
    description:
      "Портфолио Егора Трефилова — Python Backend & AI Automation Developer. Backend-системы, AI-приложения и инструменты автоматизации.",
  },
  nav: {
    about: "Обо мне",
    capabilities: "Что я делаю",
    projects: "Проекты",
    experience: "Опыт",
    stack: "Стек",
    resume: "Резюме",
    contact: "Контакты",
    menu: "Меню",
    close: "Закрыть",
  },
  loader: { forming: "Сборка ядра" },
  hero: {
    label: "Backend / AI / Automation",
    first: "Егор",
    last: "Трефилов",
    role: "Python Backend &\nAI Automation Developer",
    summary:
      "Проектирую backend-системы, AI-приложения и инструменты автоматизации — с упором на архитектуру, надёжность и реальное использование.",
    explore: "Смотреть работы",
    contact: "Написать",
    available: "Открыт к предложениям",
    locationNote: "Independent / Freelance",
  },
  about: {
    index: "01",
    label: "Обо мне",
    statement: "Системы, которые остаются полезными после демо.",
    paragraphs: [
      "Я — Егор Трефилов, Python Backend & AI Automation Developer.",
      "Мне интересны системы, которые остаются понятными после первой версии: ясные границы, предсказуемые данные и поведение, которое можно объяснить.",
      "Backend, AI и автоматизация для меня про одно и то же — превратить запутанный процесс в повторяемый.",
      "Основной стек — Python, FastAPI, PostgreSQL, SQLAlchemy, Docker и современные AI/LLM-интеграции. Также работаю с mobile, desktop и ML-проектами, когда этого требует задача.",
    ],
  },
  capabilities: {
    index: "02",
    label: "Что я делаю",
    title: "Направления",
    items: [
      {
        index: "01",
        title: "Backend-системы",
        tags: "FastAPI · PostgreSQL · REST API · Фоновые задачи",
        body: "Собираю backend-сервисы, API и системы вокруг данных — с упором на ясную архитектуру и надёжность.",
      },
      {
        index: "02",
        title: "AI-интеграции",
        tags: "LLM · RAG · AI-процессы · Обработка данных",
        body: "Встраиваю AI в рабочие продукты: LLM API, retrieval-пайплайны и автоматизация вокруг них.",
      },
      {
        index: "03",
        title: "Автоматизация",
        tags: "Боты · Парсеры · Внешние API · Процессы",
        body: "Делаю инструменты, которые связывают сервисы, обрабатывают данные и убирают ручную рутину.",
      },
      {
        index: "04",
        title: "Desktop и кроссплатформа",
        tags: "Flutter · .NET · WinUI · C++",
        body: "Десктопные и кроссплатформенные инструменты, когда задаче нужно приложение на устройстве, а не только API.",
      },
    ],
  },
  experience: {
    index: "03",
    label: "Опыт",
    title: "Сервисы, а не слайды.",
    role: "Python Backend & AI Automation Developer",
    employment: "Independent / Freelance",
    period: "Август 2025 — настоящее время",
    intro: "Независимая работа с августа 2025: backend-сервисы, AI-интеграции и практическая автоматизация.",
    tracksTitle: "Фокус",
    tracks: [
      { period: "2025 — сейчас", title: "Backend-сервисы", body: "REST API, PostgreSQL, SQLAlchemy, Alembic, аутентификация и фоновые задачи." },
      { period: "2025 — сейчас", title: "AI-интеграции", body: "LLM API, RAG-пайплайны и учёт использования AI внутри рабочих продуктов." },
      { period: "2025 — сейчас", title: "Автоматизация", body: "Telegram-боты, парсеры, внешние API и скрипты обработки данных." },
    ],
    builtTitle: "Что разрабатываю",
    built: [
      "Backend-сервисы",
      "REST API",
      "Telegram-боты",
      "Парсеры",
      "Инструменты автоматизации",
      "Сайты",
      "Скрипты обработки данных",
    ],
    practiceTitle: "На практике",
    practice: [
      "Python / FastAPI",
      "PostgreSQL",
      "SQLAlchemy",
      "Миграции Alembic",
      "Аутентификация",
      "Управление сессиями",
      "Внешние API",
      "LLM-интеграции",
      "RAG",
      "Фоновые задачи",
      "Docker",
      "CI",
      "Автотесты",
      "Скрапинг",
      "Обработка данных",
    ],
  },
  projects: {
    index: "04",
    label: "Избранные работы",
    title: "Кейсы",
    purpose: "Задача",
    built: "Что сделано",
    highlights: "Инженерия",
    technology: "Технологии",
    github: "GitHub",
    active: "В активной разработке",
    items: mergeProjects([
      {
        name: "AI Python Mentor",
        status: "В активной разработке",
        statement: "Full-stack AI-платформа для изучения Python и backend-разработки.",
        purpose:
          "Среда обучения, где AI-наставник, маршруты и практика кода живут рядом с настоящим backend.",
        built:
          "Аутентификация и сессии, миграции PostgreSQL, учебные маршруты, AI-тьютор с RAG, практика Python, фоновые задачи, учёт использования AI, интеграции email и Telegram, CI и отдельная архитектура безопасного исполнения Python.",
        highlights: [
          "Аутентификация и сессии",
          "Миграции PostgreSQL",
          "Структурированные маршруты обучения",
          "AI-тьютор и RAG",
          "Практика Python",
          "Фоновые задачи",
          "Учёт использования AI",
          "Интеграции email / Telegram",
          "CI",
          "Изолированное исполнение Python",
        ],
      },
      {
        name: "NGIE University App",
        statement: "Кроссплатформенное университетское приложение: офлайн-данные, уведомления расписания и нативные виджеты.",
        purpose: "Ежедневный инструмент для расписания, который работает офлайн и на экране блокировки.",
        built:
          "Flutter-приложение с feature-oriented архитектурой, локальным хранилищем, слоем сети и кэша, уведомлениями, iOS-виджетами включая lock screen, Android-интеграциями и mobile CI.",
        highlights: [
          "Feature-oriented архитектура",
          "Офлайн-хранилище",
          "Слой сети и кэша",
          "Расписание",
          "Уведомления",
          "Нативные iOS-виджеты",
          "Виджеты lock screen",
          "Android-интеграции",
          "Mobile CI",
        ],
      },
      {
        name: "TransactionMonitor",
        statement: "Десктопное приложение мониторинга транзакций и анализа рисков.",
        purpose: "Рабочее место для наблюдения за транзакциями, клиентами и контрагентами через призму риска.",
        built:
          "Мониторинг, risk scoring, аналитический dashboard, записи клиентов, счетов и контрагентов, анализ рисков и экспорт CSV.",
        highlights: [
          "Мониторинг транзакций",
          "Risk scoring",
          "Аналитический dashboard",
          "Клиенты, счета, контрагенты",
          "Анализ рисков",
          "Экспорт CSV",
        ],
      },
      {
        name: "Neural A* Heuristic",
        statement:
          "Нейросеть на PyTorch учится оценивать расстояние до решения и становится эвристикой для поиска A*.",
        purpose: "Заменить ручную эвристику обучаемой функцией ценности, не выходя из классического поиска.",
        built:
          "Решённые состояния откатываются назад и собираются в датасет. Нейронная функция V(s) оценивает расстояние до решения и направляет A*.",
        highlights: [
          "Решённое состояние → обратные шаги",
          "Обучающий датасет",
          "Нейронная функция V(s)",
          "Поиск A*",
          "Решение",
        ],
      },
      {
        name: "K-Nearest Neighbors from Scratch",
        statement: "Алгоритм k-NN, написанный с нуля на C++17, с десктопным интерфейсом.",
        purpose: "Прозрачный классификатор: расстояния, голоса и датасет остаются видимыми.",
        built:
          "Евклидово, манхэттенское и косинусное расстояние, взвешенное голосование, нормализация признаков, CSV-датасеты и визуализация.",
        highlights: [
          "Евклидово расстояние",
          "Манхэттенское расстояние",
          "Косинусное расстояние",
          "Взвешенное голосование",
          "Нормализация признаков",
          "CSV-датасеты",
          "Десктопная визуализация",
        ],
      },
    ]),
  },
  stack: {
    index: "05",
    label: "Технологии",
    title: "Стек, на котором я реально собираю системы.",
    groups: [
      {
        name: "Backend",
        items: ["Python", "FastAPI", "PostgreSQL", "SQLAlchemy", "Alembic", "REST API", "AsyncIO"],
      },
      {
        name: "AI / Data",
        items: ["LLM API", "RAG", "PyTorch", "Pandas", "Обработка данных", "Автоматизация"],
      },
      {
        name: "Инфраструктура",
        items: ["Docker", "Git", "GitHub Actions", "Linux", "CI"],
      },
      {
        name: "Дополнительно",
        items: ["Next.js", "TypeScript", "Flutter", "Dart", "C#", ".NET", "C++17", "Swift"],
      },
    ],
  },
  resume: {
    index: "06",
    label: "Резюме",
    title: "Коротко, на бумаге.",
    name: "Егор Трефилов",
    role: "Python Backend & AI Automation Developer",
    profileTitle: "Профиль",
    profile: "Backend-разработчик с фокусом на Python, FastAPI, PostgreSQL и AI/LLM-интеграции.",
    experienceTitle: "Опыт",
    educationTitle: "Образование",
    skillsTitle: "Ключевые навыки",
    skills: ["Python", "Backend", "FastAPI", "PostgreSQL", "Docker", "REST API", "SQLAlchemy", "AI / LLM", "RAG"],
    workTitle: "Избранные работы",
    download: "Скачать PDF",
    view: "Резюме на GitHub",
  },
  education: {
    index: "07",
    label: "Образование",
    school: "NGIEU",
    program: "Системы искусственного интеллекта",
    period: "2024 — настоящее время",
  },
  contact: {
    index: "08",
    label: "Контакты",
    title: "Давайте создадим что-нибудь полезное.",
    status: "Открыт к работе, фрилансу и сотрудничеству",
    cta: "Написать мне",
    github: "GitHub",
    copyEmail: "Скопировать почту",
    copyTelegram: "Скопировать Telegram",
    copied: "Скопировано",
    email: "Почта",
    telegram: "Telegram",
    linkedin: "LinkedIn",
    resume: "Резюме",
  },
  footer: {
    role: "Python Backend / AI / Automation",
    rights: "Егор Трефилов",
  },
  a11y: {
    themeToLight: "Включить светлую тему",
    themeToDark: "Включить тёмную тему",
    themeLight: "Светлая",
    themeDark: "Тёмная",
    lang: "Язык",
    skip: "К содержанию",
    orb: "Декоративное вычислительное ядро",
    notFound: { title: "Такой страницы нет.", body: "Адрес не совпадает ни с одним разделом сайта.", back: "На главную" },
  },
};

export default ru;
